### ISSUE TITLE
Ensure free transactions will enter in every block

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo-plugins#23]
@erikzhang, @shargon, @igormcoelho Nowadays, if there are 500 transactions with fees, no free transaction will enter in the Block.

We current have two limits:
* MaxTransactionPerBlock = 500
* MaxFreeTransaction = 20

In my opinion, if there are free transaction they should always compete between them but not with fee based transactions.
Thus, 480 fee transaction would enter and 20 free transactions as well.
If there are not 20 free transactions the ones with fee's will occupy this space.

I suggest that we change the following lines, extending mempool object to this method:
```cs
            Transaction[] array = transactions.ToArray();
            if (array.Length + 1 <= Settings.Default.MaxTransactionsPerBlock)
                return array;
            transactions = array.OrderByDescending(p => p.NetworkFee / p.Size).ThenByDescending(p => p.NetworkFee).Take(Settings.Default.MaxTransactionsPerBlock - 1);
            return FilterFree(transactions);
```

This change would allow us to move towards other implementations, such as multiples mempools, with staked transactions or other ongoing discussed strategies.

**Comment by igormcoelho** [comment]
@erikzhang @belane perhaps it's better to continue discussions on free tx here, otherwise transaction length PR will be compromised.

> So why do we let free transactions to enter the block and let the paid transactions line up?
@erikzhang I like the double queue idea, then payants compete for their slot, and free compete for their slot (perhaps with PoW, PoS, and many other ideas from community)... that guarantees business to work (at least minimally) with free tx, even when block as full. It really brings no economic advantage on payed money, that's true, but it defends the idea of having free tx on Neo. Otherwise free tx will only work when blocks are not full, which is also reasonable these days, because blocks are not being constantly filled, but may not work in a future where competition is bigger for payed tx. Just my thoughts.

**Comment by vncoelho** [comment]
https://github.com/neo-project/neo-plugins/pull/10
